// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteNote(arg1) {
  return window['go']['main']['App']['DeleteNote'](arg1);
}

export function GenerateContent(arg1) {
  return window['go']['main']['App']['GenerateContent'](arg1);
}

export function GetAIProvider() {
  return window['go']['main']['App']['GetAIProvider']();
}

export function GetPresetBackgrounds() {
  return window['go']['main']['App']['GetPresetBackgrounds']();
}

export function ListNotes() {
  return window['go']['main']['App']['ListNotes']();
}

export function LoadNote(arg1) {
  return window['go']['main']['App']['LoadNote'](arg1);
}

export function ProcessContent(arg1, arg2) {
  return window['go']['main']['App']['ProcessContent'](arg1, arg2);
}

export function SaveImage(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveImage'](arg1, arg2, arg3);
}

export function SaveNote(arg1, arg2, arg3) {
  return window['go']['main']['App']['SaveNote'](arg1, arg2, arg3);
}

export function SetGeminiAPIKey(arg1) {
  return window['go']['main']['App']['SetGeminiAPIKey'](arg1);
}

export function SetNoteBackground(arg1, arg2) {
  return window['go']['main']['App']['SetNoteBackground'](arg1, arg2);
}

export function SetNoteIcon(arg1, arg2) {
  return window['go']['main']['App']['SetNoteIcon'](arg1, arg2);
}

export function ToggleNoteFavorite(arg1) {
  return window['go']['main']['App']['ToggleNoteFavorite'](arg1);
}
