// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function DeleteNote(arg1:string):Promise<void>;

export function GenerateContent(arg1:string):Promise<string>;

export function GetAIProvider():Promise<Record<string, any>>;

export function GetPresetBackgrounds():Promise<Array<string>>;

export function ListNotes():Promise<Array<main.NoteMeta>>;

export function LoadNote(arg1:string):Promise<main.Note>;

export function ProcessContent(arg1:string,arg2:string):Promise<string>;

export function SaveImage(arg1:string,arg2:string,arg3:string):Promise<string>;

export function SaveNote(arg1:string,arg2:string,arg3:string):Promise<void>;

export function SetGeminiAPIKey(arg1:string):Promise<void>;

export function SetNoteBackground(arg1:string,arg2:string):Promise<void>;

export function SetNoteIcon(arg1:string,arg2:string):Promise<void>;

export function ToggleNoteFavorite(arg1:string):Promise<void>;
